/*
 * nn_host.cpp  —  XRT host for the hls4ml nn_top kernel on felix-155.
 * Compiled cross-compiled for aarch64 and packed into the SD card image.
 *
 * Usage (on board):
 *   /boot/nn_host /boot/nn_top.xclbin [n_samples]
 */
#define CL_HPP_CL_1_2_DEFAULT_BUILD
#define CL_HPP_TARGET_OPENCL_VERSION  120
#define CL_HPP_MINIMUM_OPENCL_VERSION 120
#define CL_HPP_ENABLE_PROGRAM_CONSTRUCTION_FROM_ARRAY_COMPATIBILITY 1

#include <CL/cl2.hpp>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <vector>
#include <string>

#define IN_FEATURES  16
#define N_CLASSES    5

// ── Embedded test data (generated by the notebook) ──────────────────────────
static const float TEST_SAMPLES[128] = {
    -0.119503f, 0.406163f, -1.040586f, -0.824731f, -0.755336f, -0.580973f, 1.986916f, 1.538063f, 1.986916f, 0.631238f, 0.383561f, -0.201305f, 1.059766f, 0.408658f, -1.019956f, -0.180167f,
    0.308873f, 0.227120f, -1.156056f, -0.846081f, -1.034614f, -0.619835f, 0.183208f, 0.595843f, 0.183208f, 1.702366f, 2.040997f, 2.422763f, 1.524450f, 1.867446f, -1.232003f, -1.194969f,
    -1.265502f, 0.667533f, 1.408745f, 1.401185f, 1.577529f, 1.292720f, 0.123505f, 0.027046f, 0.123505f, 0.328593f, 0.520602f, 0.733342f, 0.551962f, 0.582470f, 1.309233f, 1.757181f,
    -1.065062f, 0.682347f, 2.173922f, 2.234143f, 2.050646f, 2.351878f, -0.132904f, 0.228289f, -0.132904f, 0.906659f, 1.110763f, 1.612730f, 0.911719f, 1.395820f, 1.812610f, 0.973016f,
    -1.520574f, 0.877188f, 2.424016f, 2.769202f, 1.994663f, 1.780612f, -0.357901f, -0.305107f, -0.357901f, 0.524009f, 1.055208f, 1.123671f, 0.423327f, 0.368293f, 1.758365f, 1.526544f,
    -0.255080f, 0.352700f, 0.416073f, -0.027017f, 0.581978f, 0.172364f, 0.151535f, 0.234123f, 0.151535f, 0.777979f, 0.678370f, 0.886380f, 0.496985f, 0.465776f, -0.104381f, 0.557870f,
    0.489306f, -0.564569f, -0.416686f, -0.473713f, 0.158097f, -0.196374f, 1.578857f, 0.534631f, 1.578857f, -0.387797f, -0.656548f, -0.567341f, 0.343310f, 0.142657f, -0.278295f, 0.880761f,
    -0.991130f, 0.699039f, -0.331439f, -0.559354f, 0.116722f, -0.121366f, 1.064958f, 1.585005f, 1.064958f, 1.142928f, 0.756210f, 0.570443f, 1.126934f, 1.111768f, -0.217788f, 0.880761f
};

static const int GT_LABELS[8] = {1, 1, 2, 2, 2, 2, 1, 0};

static const char* CLASS_NAMES[5] = {"g", "q", "t", "w", "z"};

// ── Helpers ──────────────────────────────────────────────────────────────────
static std::vector<char> read_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) { fprintf(stderr, "ERROR: cannot open '%s'\n", path.c_str()); exit(1); }
    f.seekg(0, f.end); size_t n = f.tellg(); f.seekg(0, f.beg);
    std::vector<char> buf(n); f.read(buf.data(), n);
    return buf;
}

int main(int argc, char* argv[]) {
    if (argc < 2) { fprintf(stderr, "Usage: %s <nn_top.xclbin> [n_samples]\n", argv[0]); return 1; }
    const std::string xclbin_path = argv[1];
    const int n = (argc >= 3) ? atoi(argv[2]) : 8;

    // ── OpenCL boilerplate ───────────────────────────────────────────────────
    std::vector<cl::Platform> platforms;
    cl::Platform::get(&platforms);
    cl::Platform xilinx_plt;
    for (auto& p : platforms)
        if (p.getInfo<CL_PLATFORM_NAME>() == "Xilinx") { xilinx_plt = p; break; }

    std::vector<cl::Device> devs;
    xilinx_plt.getDevices(CL_DEVICE_TYPE_ACCELERATOR, &devs);
    if (devs.empty()) { fprintf(stderr, "ERROR: no Xilinx accelerator found\n"); return 1; }
    cl::Device device = devs[0];
    printf("Device : %s\n", device.getInfo<CL_DEVICE_NAME>().c_str());

    auto bin = read_file(xclbin_path);
    cl_int err;
    cl::Context       ctx(device, nullptr, nullptr, nullptr, &err);
    cl::Program::Binaries bins; bins.push_back({bin.data(), bin.size()});
    cl::Program       prog(ctx, {device}, bins, nullptr, &err);
    cl::CommandQueue  q(ctx, device, CL_QUEUE_PROFILING_ENABLE, &err);
    cl::Kernel        kernel(prog, "nn_top", &err);
    if (err != CL_SUCCESS) { fprintf(stderr, "Kernel load failed err=%d\n", err); return 1; }

    // ── Allocate buffers ─────────────────────────────────────────────────────
    size_t in_bytes  = (size_t)n * IN_FEATURES * sizeof(float);
    size_t out_bytes = (size_t)n * N_CLASSES   * sizeof(float);
    cl::Buffer buf_in (ctx, CL_MEM_READ_ONLY  | CL_MEM_ALLOC_HOST_PTR, in_bytes,  nullptr, &err);
    cl::Buffer buf_out(ctx, CL_MEM_WRITE_ONLY | CL_MEM_ALLOC_HOST_PTR, out_bytes, nullptr, &err);

    // ── Fill input (use embedded test samples, wrapping around if n > 8) ─
    float* in_ptr = (float*)q.enqueueMapBuffer(buf_in, CL_TRUE, CL_MAP_WRITE, 0, in_bytes, nullptr, nullptr, &err);
    for (int s = 0; s < n; s++)
        memcpy(in_ptr + s * IN_FEATURES,
               TEST_SAMPLES + (s % 8) * IN_FEATURES,
               IN_FEATURES * sizeof(float));
    q.enqueueUnmapMemObject(buf_in, in_ptr);

    // ── Run kernel ────────────────────────────────────────────────────────────
    kernel.setArg(0, buf_in);
    kernel.setArg(1, buf_out);
    kernel.setArg(2, n);

    cl::Event ev;
    q.enqueueMigrateMemObjects({buf_in},  0);
    q.enqueueTask(kernel, nullptr, &ev);
    q.enqueueMigrateMemObjects({buf_out}, CL_MIGRATE_MEM_OBJECT_HOST);
    q.finish();

    // Kernel wall-clock time
    cl_ulong t_start, t_end;
    ev.getProfilingInfo(CL_PROFILING_COMMAND_START, &t_start);
    ev.getProfilingInfo(CL_PROFILING_COMMAND_END,   &t_end);
    double ms_total = (t_end - t_start) * 1e-6;

    // ── Read results ──────────────────────────────────────────────────────────
    float* out_ptr = (float*)q.enqueueMapBuffer(buf_out, CL_TRUE, CL_MAP_READ, 0, out_bytes, nullptr, nullptr, &err);

    int correct = 0;
    printf("\n%-6s  %-10s  %-10s  Scores\n", "Sample", "Pred", "GT");
    printf("%s\n", std::string(60, '-').c_str());
    for (int s = 0; s < n; s++) {
        const float* scores = out_ptr + s * N_CLASSES;
        int pred = 0;
        for (int c = 1; c < N_CLASSES; c++)
            if (scores[c] > scores[pred]) pred = c;
        int gt = GT_LABELS[s % 8];
        if (pred == gt) correct++;
        printf("%-6d  %-10s  %-10s  ", s, CLASS_NAMES[pred], CLASS_NAMES[gt]);
        for (int c = 0; c < N_CLASSES; c++) printf("%.3f ", scores[c]);
        printf("%s\n", pred == gt ? "[OK]" : "[X]");
    }
    printf("%s\n", std::string(60, '-').c_str());
    printf("Accuracy    : %d / %d = %.1f%%\n", correct, n, 100.0*correct/n);
    printf("Kernel time : %.3f ms  (%.3f ms/sample)\n", ms_total, ms_total/n);

    q.enqueueUnmapMemObject(buf_out, out_ptr);
    q.finish();
    return 0;
}
